# Generated by Django 3.0.7 on 2020-06-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='to be changed', unique=True),
            preserve_default=False,
        ),
    ]
