# Generated by Django 3.0.6 on 2020-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200528_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, to='chat.Car'),
        ),
    ]
