# Generated by Django 3.0.6 on 2020-05-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200531_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default='no', on_delete=django.db.models.deletion.CASCADE, to='chat.User'),
        ),
    ]
