# Generated by Django 3.0.6 on 2020-06-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20200602_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='enrolled_students',
        ),
        migrations.AddField(
            model_name='courses',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, null=True, to='subject.Student'),
        ),
    ]
