# Generated by Django 3.0.6 on 2020-06-01 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_auto_20200602_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='offered_to',
        ),
        migrations.AddField(
            model_name='courses',
            name='offered_to_BBA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='offered_to_acf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='offered_to_eco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='offered_to_ecomath',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollmentbba',
            name='course_1',
            field=models.ForeignKey(limit_choices_to={'offerend_to_BBA': True}, on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='subject.Courses'),
        ),
        migrations.AlterField(
            model_name='enrollmentbba',
            name='course_2',
            field=models.ForeignKey(limit_choices_to={'offerend_to_BBA': True}, on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='subject.Courses'),
        ),
        migrations.AlterField(
            model_name='enrollmentbba',
            name='course_3',
            field=models.ForeignKey(limit_choices_to={'offerend_to_BBA': True}, on_delete=django.db.models.deletion.CASCADE, related_name='course3', to='subject.Courses'),
        ),
        migrations.AlterField(
            model_name='enrollmentbba',
            name='course_4',
            field=models.ForeignKey(limit_choices_to={'offerend_to_BBA': True}, on_delete=django.db.models.deletion.CASCADE, related_name='course4', to='subject.Courses'),
        ),
        migrations.AlterField(
            model_name='enrollmentbba',
            name='course_5',
            field=models.ForeignKey(limit_choices_to={'offerend_to_BBA': True}, on_delete=django.db.models.deletion.CASCADE, related_name='course5', to='subject.Courses'),
        ),
    ]
